### ISSUE TITLE
Kotlin support

### ISSUE THREAD

**Issue by gmartinsvrf** [mitchtabian/Dagger-Examples#2]
Hi, first of all, that's a great sample and I really appreciate your effort in it.

So, I'm trying to build an application which is very similar to your sample, however it won't build. It's written in Kotlin btw. I just wonder if you would be able to help?

I keep getting this error and I can't figure it out:

`AppComponent.java:8: error: [Dagger/MissingBinding] java.util.Map<java.lang.Class<? extends androidx.lifecycle.ViewModel>,javax.inject.Provider<androidx.lifecycle.ViewModel>> cannot be provided without an @Provides-annotated method.
public abstract interface AppComponent extends dagger.android.AndroidInjector<com.vrify.vrify.VrifyApp> {
                ^
      java.util.Map<java.lang.Class<? extends androidx.lifecycle.ViewModel>,javax.inject.Provider<androidx.lifecycle.ViewModel>> is injected at
          com.vrify.vrify.core.viewmodel.ViewModelFactory(creators)
      com.vrify.vrify.core.viewmodel.ViewModelFactory is injected at
          com.vrify.vrify.core.di.ViewModelFactoryModule.bindViewModelFactory(factory)
      androidx.lifecycle.ViewModelProvider.Factory is injected at
          com.vrify.vrify.discover.ui.CompanyListFragment.viewModelFactory
      com.vrify.vrify.discover.ui.CompanyListFragment is injected at
          dagger.android.AndroidInjector.inject(T) [com.vrify.vrify.core.AppComponent → com.vrify.vrify.core.di.MainActivityBuildersModule_ContributeMainActivity.MainActivitySubcomponent → com.vrify.vrify.discover.di.MainActivityFragmentBuildersModule_ContributeCompanyListFragment.CompanyListFragmentSubcomponent]`

Take care

**Comment by houman-sanati** [comment]
for kotlin use this code as `ViewModelProviderFactory` class: 

```
class ViewModelProviderFactory @Inject constructor(
        private val creators: Map<Class<out ViewModel>, @JvmSuppressWildcards Provider<ViewModel>>
) : ViewModelProvider.Factory {
    override fun <T : ViewModel> create(modelClass: Class<T>): T {
        val creator = creators[modelClass] ?: creators.entries.firstOrNull {
            modelClass.isAssignableFrom(it.key)
        }?.value ?: throw IllegalArgumentException("unknown model class $modelClass")
        try {
            @Suppress("UNCHECKED_CAST")
            return creator.get() as T
        } catch (e: Exception) {
            throw RuntimeException(e)
        }
    }
}
```

**Comment by gmartinsvrf** [comment]
I'm already using that class. Doesn't work.

Thanks anyways ...

**Comment by mitchtabian** [comment]
Link your MainViewModelsModule and AuthViewModelsModule

**Comment by gmartinsvrf** [comment]
I'm sorry but I've already taken another approach. Working with multi-modules now instead of subcomponents.

I believe the issue was that I can't have a subcomponent rely on its parent component's content. Either that or something to do with Kotlin ...

I appreciate your help though :)
