### ISSUE TITLE
Without ViewModelFactoryModule, AuthViewModel is still injected properly.

### ISSUE THREAD

**Issue by ghost** [mitchtabian/Dagger-Examples#7]
Hello!
Please checkout the branch **map-multibindings-and-viewmodels** first!!

I commented out all the **ViewModelFactoryModule** class code and excluded the module from the **AppComponent**. And the **AuthViewModel** is still injected!!

Does anyone know why????

**Comment by haitrvn** [comment]
If your ViewModel just need create new instance with no param in constuctor(example: new SomeViewModel();) then you don't need Factory, but when you create new ViewModel with param (example: new SomeViewModel(someParam mParam);) you need Factory to pass your param through. 
Sorry my English bad.

**Comment by ghost** [comment]
@haitrvnvn Thank you!! I fully understand!!
